### ISSUE TITLE
Deployment guides for different platforms and services

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs.influxdata.com#2063]
This issue combines several related issues into a single to-do list.

- [ ] Document how to deploy Influx Enterprise to IBM Cloud (https://github.com/influxdata/docs.influxdata.com/issues/1826)
- [ ] Document how to deploy Influx Enterprise on Azure cloud (https://github.com/influxdata/docs.influxdata.com/issues/1825)
- [ ] Document how to deploy influx enterprise on google cloud infrastructure (https://github.com/influxdata/docs.influxdata.com/issues/1824)
- [ ] Document how to deploy Influx to AWS using Terraform (https://github.com/influxdata/docs.influxdata.com/issues/1823)
- [ ] Document deployment to Kubernetes (https://github.com/influxdata/docs.influxdata.com/issues/1565)
- [ ] Document how to configure and set up the tick stack locally in docker (https://github.com/influxdata/docs.influxdata.com/issues/1612)
- [ ] Document how to configure and set up the tick stack on kubernetes (include configs) (https://github.com/influxdata/docs.influxdata.com/issues/1612)
  - [ ] Telegraf as a sidecar and a daemonset (https://github.com/influxdata/docs.influxdata.com/issues/1612)
  - [ ] InfluxDB, Chronograf, Kapacitor with persistent volumes (https://github.com/influxdata/docs.influxdata.com/issues/1612)
- [ ] Document how to configure and set up the tick stack on Amazon EKS https://aws.amazon.com/eks/ (include configs) (should be very similar to others) (https://github.com/influxdata/docs.influxdata.com/issues/1612)
- [ ] Document how to configure and set up the tick stack on OpenShift (include configs) (should be very similar to others) (https://github.com/influxdata/docs.influxdata.com/issues/1612)
